import { Book } from "@/types/book"

export const books: Book[] = [
   {
        id: 1,
        slug: "the-handmaids-tale-by-margaret-atwood",
        title: "The Handmaid's Tale",
        author: "Margaret Atwood",
        pages: 311,
        description: "The Handmaid's Tale is a futuristic dystopian novel by Canadian author Margaret Atwood published in 1985. It is set in a near-future New England in a patriarchal, totalitarian theonomic state known as the Republic of Gilead, which has overthrown the United States government.",
        image: "/books/the-handmaids-tale-by-margaret-atwood.jpg",
        genre: ["Novel", "Science fiction", "Speculative fiction", "Dystopian Fiction", "Fantasy Fiction", "Tragedy", "Feminist science fiction"],
    },
    {
        id: 2,
        slug: "the-mist-by-stephen-king",
        title: "The Mist",
        author: "Stephen King",
        pages: 230,
        description: "The Mist is a science fiction psychological horror novella by American author Stephen King. First published by Viking Press in 1980 as part of the Dark Forces anthology, an edited version was subsequently included in King's 1985 collection Skeleton Crew.",
        image: "/books/the-mist-by-stephen-king.jpg",
        genre: ["Horror fiction", "Novel", "Novella", "Science fiction"],
    },
    {
        id: 3,
        slug: "normal-people-by-sally-rooney",
        title: "Normal People",
        author: "Sally Rooney",
        pages: 304,
        description: "Normal People is a 2018 novel by the Irish author Sally Rooney. Normal People is Rooney's second novel, published after Conversations with Friends. It was first published by Faber & Faber on 30 August 2018.",
        image: "/books/normal-people-by-sally-rooney.jpg",
        genre: ["Novel", "Literary fiction"],
    },
    {
        id: 4,
        slug: "sense-and-sensibility-by-jane-austen",
        title: "Sense and Sensibility",
        author: "Jane Austen",
        pages: 368,
        description: "Sense and Sensibility is the first novel by the English author Jane Austen, published in 1811. It was published anonymously: By A Lady appears on the title page where the author's name might have been.",
        image: "/books/sense-and-sensibility-by-jane-austen.jpg",
        genre: ["Novel", "Romance novel", "Fiction"],
    },
    {
        id: 5,
        slug: "the-midnight-library-by-matt-haig",
        title: "The Midnight Library",
        author: "Matt Haig",
        pages: 304,
        description: "The Midnight Library is a fantasy novel by Matt Haig, published on 13 August 2020 by Canongate Books. It was abridged and broadcast on BBC Radio 4 over ten episodes in December 2020.",
        image: "/books/the-midnight-library-by-matt-haig.jpg",
        genre: ["Science fiction", "Fantasy Fiction", "Philosophical fiction"],
    },
    {
        id: 6,
        slug: "the-graveyard-book-by-neil-gaiman",
        title: "The Graveyard Book",
        author: "Neil Gaiman",
        pages: 312,
        description: "The Graveyard Book is a young adult novel written by the English author Neil Gaiman, simultaneously published in the United Kingdom and in the United States in 2008.",
        image: "/books/the-graveyard-book-by-neil-gaiman.jpg",
        genre: ["Novel", "Fantasy Fiction", "Horror fiction", "Young adult literature", "Paranormal fiction"],
    },
];
