import { Book, BookStatus } from "@/types/book";

export const books: Book[] = [
    {
        id: 1,
        slug: "the-handmaids-tale-by-margaret-atwood",
        title: "The Handmaid's Tale",
        author: "Margaret Atwood",
        pages: 311,
        description: "The Handmaid's Tale is a futuristic dystopian novel by Canadian author Margaret Atwood published in 1985. It is set in a near-future New England in a patriarchal, totalitarian theonomic state known as the Republic of Gilead, which has overthrown the United States government.",
        cover: "/books/the-handmaids-tale-by-margaret-atwood.jpg",
        coverDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        genres: ["Novel", "Science fiction", "Speculative fiction", "Dystopian Fiction", "Fantasy Fiction", "Tragedy", "Feminist science fiction"],
        rating: 4.5,
        status: BookStatus.Completed,
    },
    {
        id: 2,
        slug: "the-mist-by-stephen-king",
        title: "The Mist",
        author: "Stephen King",
        pages: 230,
        description: "The Mist is a science fiction psychological horror novella by American author Stephen King. First published by Viking Press in 1980 as part of the Dark Forces anthology, an edited version was subsequently included in King's 1985 collection Skeleton Crew.",
        cover: "/books/the-mist-by-stephen-king.jpg",
        coverDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        genres: ["Horror fiction", "Novel", "Novella", "Science fiction"],
        rating: 4.6,
        status: BookStatus.Completed,
    },
    {
        id: 3,
        slug: "normal-people-by-sally-rooney",
        title: "Normal People",
        author: "Sally Rooney",
        pages: 304,
        description: "Normal People is a 2018 novel by the Irish author Sally Rooney. Normal People is Rooney's second novel, published after Conversations with Friends. It was first published by Faber & Faber on 30 August 2018.",
        cover: "/books/normal-people-by-sally-rooney.jpg",
        coverDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        genres: ["Novel", "Literary fiction"],
        rating: 4.7,
        status: BookStatus.Completed,
    },
    {
        id: 4,
        slug: "sense-and-sensibility-by-jane-austen",
        title: "Sense and Sensibility",
        author: "Jane Austen",
        pages: 368,
        description: "Sense and Sensibility is the first novel by the English author Jane Austen, published in 1811. It was published anonymously: By A Lady appears on the title page where the author's name might have been.",
        cover: "/books/sense-and-sensibility-by-jane-austen.jpg",
        coverDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        genres: ["Novel", "Romance novel", "Fiction"],
        rating: 4.8,
        status: BookStatus.Completed,
    },
    {
        id: 5,
        slug: "the-midnight-library-by-matt-haig",
        title: "The Midnight Library",
        author: "Matt Haig",
        pages: 304,
        description: "The Midnight Library is a fantasy novel by Matt Haig, published on 13 August 2020 by Canongate Books. It was abridged and broadcast on BBC Radio 4 over ten episodes in December 2020.",
        cover: "/books/the-midnight-library-by-matt-haig.jpg",
        coverDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        genres: ["Science fiction", "Fantasy Fiction", "Philosophical fiction"],
        rating: 4.9,
        status: BookStatus.Completed,
    },
    {
        id: 6,
        slug: "the-graveyard-book-by-neil-gaiman",
        title: "The Graveyard Book",
        author: "Neil Gaiman",
        pages: 312,
        description: "The Graveyard Book is a young adult novel written by the English author Neil Gaiman, simultaneously published in the United Kingdom and in the United States in 2008.",
        cover: "/books/the-graveyard-book-by-neil-gaiman.jpg",
        coverDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        genres: ["Novel", "Fantasy Fiction", "Horror fiction", "Young adult literature", "Paranormal fiction"],
        rating: 5.0,
        status: BookStatus.Completed,
    },
    {
        id: 7,
        slug: "not-quite-dead-yet-by-holly-jackson",
        title: "Not Quite Dead Yet",
        author: "Holly Jackson",
        pages: 400,
        description: "From the #1 New York Times bestselling author of A Good Girl's Guide to Murder. The stunning hardcover of Not Quite Dead features a custom-stamped case, beautiful endpapers, and a premium dust jacket!In seven days Jet Mason will be dead. Jet is the daughter of one of the wealthiest families in Woodstock, Vermont.",
        cover: "/books/not-quite-dead-yet-by-holly-jackson.jpg",
        coverDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        genres: ["Thriller", "Fiction", "Mystery", "Suspense", "Psychological thriller"],
        rating: 4.2,
        status: BookStatus.Ongoing,
        currentPage: 123,
        startDate: "2025-09-14",
        expectedFinish: "2025-09-28",
        reviewDate: "2025-10-05",
    },
];
